// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	domain "meeting-room-booking/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// BookingRepository is an autogenerated mock type for the BookingRepository type
type BookingRepository struct {
	mock.Mock
}

type BookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BookingRepository) EXPECT() *BookingRepository_Expecter {
	return &BookingRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: booking
func (_m *BookingRepository) Create(booking domain.Booking) error {
	ret := _m.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BookingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - booking domain.Booking
func (_e *BookingRepository_Expecter) Create(booking interface{}) *BookingRepository_Create_Call {
	return &BookingRepository_Create_Call{Call: _e.mock.On("Create", booking)}
}

func (_c *BookingRepository_Create_Call) Run(run func(booking domain.Booking)) *BookingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Booking))
	})
	return _c
}

func (_c *BookingRepository_Create_Call) Return(_a0 error) *BookingRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookingRepository_Create_Call) RunAndReturn(run func(domain.Booking) error) *BookingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *BookingRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookingRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BookingRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *BookingRepository_Expecter) Delete(id interface{}) *BookingRepository_Delete_Call {
	return &BookingRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *BookingRepository_Delete_Call) Run(run func(id int)) *BookingRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *BookingRepository_Delete_Call) Return(_a0 error) *BookingRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookingRepository_Delete_Call) RunAndReturn(run func(int) error) *BookingRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *BookingRepository) GetAll() ([]domain.Booking, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Booking, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Booking); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type BookingRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *BookingRepository_Expecter) GetAll() *BookingRepository_GetAll_Call {
	return &BookingRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *BookingRepository_GetAll_Call) Run(run func()) *BookingRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BookingRepository_GetAll_Call) Return(_a0 []domain.Booking, _a1 error) *BookingRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingRepository_GetAll_Call) RunAndReturn(run func() ([]domain.Booking, error)) *BookingRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *BookingRepository) GetByID(id int) (*domain.Booking, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Booking, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Booking); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type BookingRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *BookingRepository_Expecter) GetByID(id interface{}) *BookingRepository_GetByID_Call {
	return &BookingRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *BookingRepository_GetByID_Call) Run(run func(id int)) *BookingRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *BookingRepository_GetByID_Call) Return(_a0 *domain.Booking, _a1 error) *BookingRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingRepository_GetByID_Call) RunAndReturn(run func(int) (*domain.Booking, error)) *BookingRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: booking
func (_m *BookingRepository) Update(booking domain.Booking) error {
	ret := _m.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookingRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type BookingRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - booking domain.Booking
func (_e *BookingRepository_Expecter) Update(booking interface{}) *BookingRepository_Update_Call {
	return &BookingRepository_Update_Call{Call: _e.mock.On("Update", booking)}
}

func (_c *BookingRepository_Update_Call) Run(run func(booking domain.Booking)) *BookingRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Booking))
	})
	return _c
}

func (_c *BookingRepository_Update_Call) Return(_a0 error) *BookingRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookingRepository_Update_Call) RunAndReturn(run func(domain.Booking) error) *BookingRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewBookingRepository creates a new instance of BookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingRepository {
	mock := &BookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
